### ISSUE TITLE
Unable to read reference sequence base past end of current cached sequence.

### ISSUE THREAD

**Issue by chapmanb** [ekg/freebayes#165] opened 2015-04-23 19:14 UTC
Erik;
I was working on validating the latest head today and ran into issues like:
```
Exception: Unable to read reference sequence base past end of current cached sequence.
```
I know you checked in a fix to address this (https://github.com/ekg/freebayes/commit/c5efe19a4eb40ce6c1f6ef82c67bb766d319c0f6), but I'm still finding issues with this included.

Here's a reproducible test case with a small shell script. You should only need to adjust the path to GRCh37:

https://s3.amazonaws.com/chapmanb/fb/freebayes_pastend.tar.gz

While reducing this, I noticed that the command will work okay with no changed parameters but not with `--min-repeat-entropy 1`:
```
freebayes -f $ref -b reads.bam --targets regions.bed > ok.vcf
freebayes -f $ref -b reads.bam --targets regions.bed --min-repeat-entropy 1 > fail.vcf
```
So this raises a couple of issues:

- There are still some edge cases causing this problem, which this hopefully helps identify.
- Should I still be using `--min-repeat-entropy`? I added it based on this discussion (https://groups.google.com/forum/#!msg/freebayes/GvxIzjcpbas/1G6e3ArxQ4cJ) but I don't know where that stands with the latest development work.

Please let me know if any other information would be useful. Thanks much.

**Comment by chapmanb** [comment] 2015-04-25 09:28
Erik;
I put together a validation of the latest FreeBayes head (0.9.21-13) versus Genome in a Bottle using single, pooled and joint calling. This removed `--min-repeat-entropy` so I'd avoid the error above. It looks like something is problematic with the latest set of changes as they are much less sensitive than the previous evaluation. Here's the 0.9.21-13 comparison:

http://imgur.com/a/hQAps

and here is 0.9.21-7:

http://imgur.com/a/ancGz

Hope this helps and happy to provide more details. Thanks as always for all the great work on FreeBayes.

**Comment by ekg** [comment] 2015-04-25 18:04
Thanks Brad. At least we know which version is functioning better, so I can
compare them to see what might be triggering this.

**Comment by ekg** [comment] 2015-05-05 09:42
Do you have the commit id for 0.9.21-7. I can dig around to figure it out.

**Comment by chapmanb** [comment] 2015-05-05 09:49
Erik;
Thanks so much. Here is 0.9.21-7, that works as expected:

https://github.com/ekg/freebayes/commit/7dd41dbc8c789d5a82288bbafc983ad525f04061

and 0.9.21-13 was problematic:

https://github.com/ekg/freebayes/commit/c5efe19a4eb40ce6c1f6ef82c67bb766d319c0f6

**Comment by kahot** [comment] 2015-05-18 21:52
Hi Erik,
I am still having the same error as above with either using 7dd41db or c5efe19 when I try to call variants. An interesting thing is that 5 out of 10 samples ran without errors while the rest of samples keep returning the error looking like below using the same reference file:

----------------------------------------------------------------------------------------------------------------------------
Exception: Unable to read reference sequence base past end of current cached sequence.
isotig04815:22
21-324
alignment: CTCCCTCGGATTTTCAAGGGCCGTCGAAAGCGCACCGGACCCCACAAGAAGTGTGGGGCTTTACCGGACGTGAAACCCTATCTCCGGCTAAACCGATTTCAGGGTGACAGCCCGTTAAAAAGAAAAGAGAACTCTTCCCGGGGCTCTCGCCGACGTCTCCGAGTTCGGTTGCGTTACCGCTGGTG----CCACTAG--GTGGCAGTATCCCTGTTCTGGTTCGGGAATATTAACCCGATTCCCTTTCGATAGGCGGCCCAAGATTGGGCACTTTGTAACGGAATTTCCCTATCTCTTAGGATC
currentSequence: CTCCCGCGGATTTTCAAGGGCCTCCCGCGGATTTTCAAGGGCCGTCGAGAACGCACCGGACACCACAAGAAGTGTGGTGCTTTACCAGGCATTAAACCCTATCTCCGGACAATCCGATTTCAGGGTGAAAGCCTGTTAAAAAGAAAAGAGAACTCTTTCCGGGGCCCCCGCCGGCGTCTCCGCGTTCGGTTGCGTTGCCGCACTTGCCACCCACGAGGAGTGGCAATATCCGTGTTCCGGTTCGGGAATATTAACCCGATTCCCTTTCGATAGACGGCCCAAGATTGGGCACTTTGACACGGAGTTTCCCTATCTCTTAGG
currentSequence matching:
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted

I was curious if you have any suggestion what to do with this issue. Any comment/suggestion will be appreciated. Thank you for your time.
KT

**Comment by ekg** [comment] 2015-05-20 00:05
The problem is dependent on the use of `--targets`. So this seems to relate to issues with running whole-genome vs. targeted analysis producing different (or broken) results. I think I see what's going on. The jump of target regions is resetting the cached reference sequence (which should be the entire chromosome now). Then the entropy calculation is trying to examine bits of the reference and thus causes the crash.

I should have a fix for this soon, although I'm very concerned about @chapmanb 's report of regressions in sensitivity. I'm not sure what's going on there as in the test provided I don't detect any difference in the output of 7dd41db and c5efe19. That said, numerical instabilities with very small probabilities seem to be yielding minutely different QUAL values for some sites, which makes comparison a bit of a pain. I can run on a larger dataset but I'm feeling like this problem is more related to mishandling the `--targets` case than something fundamental about the operation of the model.

**Closed** 2015-05-20 12:22 UTC
