### ISSUE TITLE
"--region" in v0.9.21 does not work

### ISSUE THREAD

**Issue by lh3** [ekg/freebayes#155] opened 2015-03-10 17:35 UTC
I am calling variants on a chromosome with:
```sh
freebayes -f ref.fa -r 2 aln.bam
```
After a few minutes, the process finished but the output only contains header lines. Freebayes seems to work fine without `-r`. v0.9.20 does not have this problem.

**Comment by lh3** [comment] 2015-03-11 14:33
Pinging @tsibley in case he has a clue. I saw two PRs related to region between v0.9.20 and v0.9.21.

**Comment by ekg** [comment] 2015-03-11 14:37
A possibly-related problem is that a recent change made it so that freebayes would count up through the entire target region, even if there weren't alignments for some time. This can be slow.

I have a fix in hand to resolve this. But I don't know if it addresses the problem here, which is that the program exits without producing any output.

**Comment by ekg** [comment] 2015-03-11 14:39
I've pushed the fix in https://github.com/ekg/freebayes/commit/e4b523d0d835be6cc4320ea7692b81982af035d4

Please let me know if this resolves the problem, or we can try to coordinate a better test case. I'm not able to reproduce anything like the issue as of this commit. Again, in my case the process seems to hang (as it counts up to a point where there are alignments), but it does not exit without producing any output. A particularly bad chromosome is human 22, where a large region of the start is empty and will have no alignments.

**Comment by lh3** [comment] 2015-03-11 14:52
This fixes the issue. Note that at my hand, v0.9.21 finished in a few minutes, outputting a header-only VCF. I was testing on chr18. The first reported SNP is at 18:10006. There are no long assembly gaps.

Anyway, I am closing this issue.

**Comment by ekg** [comment] 2015-03-11 14:54
@lh3 Thanks for letting me know.

I'm trying to figure out how to include tests like this in the travis-CI ones. The problem is that we need a lot of data in order to do so, and it's hard to store much data in git or in a way that can be quickly downloaded by the continuous integration service.

**Comment by tsibley** [comment] 2015-03-11 17:50
Glad the issue is resolved!

@ekg Would it be faster/possible to generate the test data sets on the fly?

**Comment by lh3** [comment] 2015-03-11 19:58
I am reopening this issue. The fix only works in one case but not others. Now this command line:
```sh
freebayes-e4b523d -r 6:159667058-171055068 -f hs37d5.fa CHM1.bt2.bam
```
gives a header-only VCF in ~15 CPU seconds, but 0.9.20 is emitting a lot of SNP calls.

**Comment by lh3** [comment] 2015-03-11 20:03
I will use another example:
```sh
freebayes-e4b523d -r 9:67340340-83440068 -f hs37d5.fa CHM1.mem.bam
```
The CHM1.mem.bam alignment is available at:

ftp://ftp.broadinstitute.org/hapdip/

Again on this example, 0.9.20 gives SNPs, but 0.9.21 or e4b523d outputs header-only VCF.

**Comment by ekg** [comment] 2015-03-11 20:04
All right. Thanks for the

Can I rely on the URL of that alignment data? I'd like to include these as
a test case.

**Comment by lh3** [comment] 2015-03-11 20:06
(I have updated the ftp link)

That is just a temporary place for the data, unfortunately. I have not found a permanent home for the CHM1 alignment.

**Comment by lh3** [comment] 2015-03-11 20:18
I have made a smaller example and put it at:

ftp://hengli-data:lh3data@ftp.broadinstitute.org/hapdip/tmp

You will get a header-only VCF with the following command line:
```
freebayes-e4b523d -r 9:67340340-68340340 -f hs37d5.fa 1.bam
```

**Comment by ekg** [comment] 2015-03-11 21:45
@lh3 I'm not finding this easy to access. I'll just try this on the previous file.

**Comment by tsibley** [comment] 2015-03-11 23:35
@ekg `wget -r 'ftp://hengli-data:lh3data@ftp.broadinstitute.org/tmp'` will download the whole directory that @lh3 linked to.

**Comment by ekg** [comment] 2015-03-11 23:38
Ah! Thanks, the URL was different and doesn't seem to work.

**Comment by ekg** [comment] 2015-03-11 23:42
OK, I can reproduce. Thanks again.

**Comment by chapmanb** [comment] 2015-03-13 01:10
Erik and Thomas;
For what it's worth, I can confirm issues with the latest GitHub version. It only reports ~10% of calls on a full WGS analysis with regional (250k variants versus 2.8 million), so it appears to be a global issue. On the positive side, all of the calling approaches (single, pooled, joint) ran without any errors. If you need more error cases than Heng's I can put some together. Thanks again for looking at this.

**Comment by ekg** [comment] 2015-03-24 16:51
@chapmanb @lh3 @tsibley OK, this last commit should resolve the issue as far as I'm able to test. Would you let me know if it seems to resolve things. It's a small change with a big effect.

**Comment by ekg** [comment] 2015-03-24 16:52
It's not completely resolved, as tests are failing.

**Closed** 2015-03-24 17:03 UTC

**Comment by chapmanb** [comment] 2015-03-30 09:54
Erik;
Thanks much for these fixes. The latest version (0.9.21-7) validated great in the NA12878 trio evaluations for both pooled (all BAMs together) and joint (recalling based) approaches: http://imgur.com/a/ancGz. Thank you again for all the work on FreeBayes.

**Comment by ekg** [comment] 2015-03-30 10:02
Hi Brad,

Thanks for letting me know! The results look nice, and I'm curious what
hard filters you are applying to the results. Do you have a pointer to the
code that does the filtering? I think other people might be interested.

Thanks for working on the other side: using freebayes in a production
environment and reporting the problems you encounter is half of the battle.

**Comment by chapmanb** [comment] 2015-03-30 13:13
Erik;
I'm glad it's useful. As always, happy to help supplement all the great work y'all do on FreeBayes. This is essentially the same approaches used in this post (http://bcb.io/2014/10/07/joint-calling/) with updated software versions. The actual code for hard filtering is here:

https://github.com/chapmanb/bcbio-nextgen/blob/b4af45059c11c776ba834f4ef5941b6aa163ca94/bcbio/variation/vfilter.py#L121

The primary filter removes low coverage, low quality calls, filtering heterozygotes more aggressively. There is also a high depth filter based on Heng's work. Thanks again.

**Comment by WimS83** [comment] 2015-09-10 12:17
Hi, 

Do you have download link for the 0.9.21-7 version? I can not find a tag with that name or the commit id v0.9.21-7-g7dd41db (the name I found in bcbio).  

Which version do you currently recommend to use in a production environment?

**Comment by chapmanb** [comment] 2015-09-10 13:14
We still use 0.9.21-7 in bcbio for production. There's a block issue with the latest version (#173) so I haven't validated against the latest head. There isn't a tag or specific download link since FreeBayes uses submodules which aren't in the pre-baked tarballs GitHub provides for specific revisions, so it requires a recursive retrieval. You can use the homebrew recipe we have with bcbio if this helps:

https://github.com/chapmanb/homebrew-cbl/blob/master/freebayes.rb

**Comment by tsibley** [comment] 2015-09-10 14:15
> Do you have download link for the 0.9.21-7 version? I can not find a tag with that name or the commit id v0.9.21-7-g7dd41db (the name I found in bcbio).
> 
v0.9.21-7-g7dd41db refers to commit 7dd41db, which is 7 commits after the last tag (v0.9.21).

**Comment by WimS83** [comment] 2015-09-11 07:09
Thank you Thomas and Brad!

**Comment by mfresende** [comment] 2016-09-26 21:27
Hi Erik et al.,

I may be facing again the same issue with version 
##source=freeBayes v1.0.2-6-g3ce827d

It is working fine without --targets, but it outputs empty VCFs when I define the targets. For context, this is a pretty large genome (non-human) and a large number of BAM files. We still receive warning similar to #119 , but historically this did not affect the outputs.
I can try to create some examples, but I thought I would drop a note here first to check if there is any advise at this point.

Thank you,
Marcio Resende
